name: dscturk_github_io
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  flutter_markdown: any

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  osaka: any

flutter:
  uses-material-design: true

  assets:
    - assets/images/gd_dsc_lockup_color.png